// dev endpoints for "REST Client" vs extension

POST https://localhost:8080/register
content-type: application/json

{
  "username": "Moulinette",
  "email": "moulinette@42.fr",
  "password": "lol123"
}

###

POST https://localhost:8080/login
content-type: application/json

{
  "username": "Moulinette",
  "password": "lol123"
}